name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ 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 }}
        run: |
          git push --force https://huggingface.co/spaces/P-W-D-703/FedAcq-RAG-Chatbot main
